version: "3"
services:
    chainlink:
        image: smartcontract/chainlink
        env_file: ./.chainlink-${network}/.env
        ports:
            - "6688:6688"
        container_name: chainlink_${network}
        volumes:
            - "${PWD}/.chainlink-${network}:/chainlink"
        restart: on-failure:5
        entrypoint: sh -c "chainlink local import /chainlink/keyfile && chainlink local n -p /chainlink/.password -a /chainlink/.api"        # command: local import /chainlink/keyfile
        networks:
            - app-network

    bridge_db:
        image: postgres:alpine
        command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
        ports:
            - "6689:5432"
        environment:
            POSTGRES_DB: mydb
            POSTGRES_USER: user
            POSTGRES_PASSWORD: secret
        volumes:
            - "./ca/server.crt:/var/lib/postgresql/server.crt:ro"
            - "./ca/server.key:/var/lib/postgresql/server.key:ro"
            - "${PWD}/db:/var/lib/postgresql/data"
        networks:
            - app-network

    ethnode:
        image: trufflesuite/ganache-cli:latest
        ports:
            - "6690:8545"
        container_name: ganache
        networks:
            - app-network

    swipswapbalance:
        image: swipswapbalance
        ports:
            - "6691:3002"
        container_name: swipswapbalance
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
